# Generated by Django 4.1.2 on 2022-10-19 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="team",
            field=models.CharField(
                choices=[
                    ("Management", "Management"),
                    ("Sales", "Sales"),
                    ("Support", "Support"),
                ],
                default="Support",
                help_text="Choisir l'équipe de cet employé.",
                max_length=10,
            ),
        ),
    ]
