# Generated by Django 4.1.2 on 2022-10-21 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_user_team"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="team",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Management", "Management"),
                    ("Sales", "Sales"),
                    ("Support", "Support"),
                ],
                help_text="Choisir l'équipe de cet employé.",
                max_length=10,
            ),
        ),
    ]
