# Generated by Django 4.1.2 on 2022-11-10 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="client",
            options={"ordering": ["-date_created"]},
        ),
        migrations.AlterModelOptions(
            name="contract",
            options={"ordering": ["-date_created"]},
        ),
        migrations.AlterModelOptions(
            name="event",
            options={"ordering": ["-date_created"]},
        ),
    ]
