# Generated by Django 4.1.2 on 2022-11-12 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0002_alter_client_options_alter_contract_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contract",
            name="event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="business.event",
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="payment_due",
            field=models.DateField(),
        ),
    ]
